# Generated by Django 6.0.2 on 2026-02-27 23:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErdenizAPIKey',
            fields=[
                ('key_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prefix', models.CharField(db_index=True, max_length=8, unique=True)),
                ('hashed_key', models.CharField(max_length=255)),
                ('project', models.CharField(max_length=50)),
                ('permissions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'is_active'], name='erdeniz_sec_project_7ada41_idx'), models.Index(fields=['prefix'], name='erdeniz_sec_prefix_f4b7b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(choices=[('ENCRYPT', 'Veri Şifrelendi'), ('DECRYPT', 'Veri Çözüldü'), ('AUTH_SUCCESS', 'Başarılı Giriş'), ('AUTH_FAIL', 'Başarısız Giriş'), ('KEY_ROTATE', 'Anahtar Rotasyonu'), ('ENV_ENCRYPT', '.env Şifrelendi'), ('ENV_DECRYPT', '.env Çözüldü'), ('FILE_ENCRYPT', 'Dosya Şifrelendi'), ('FILE_DECRYPT', 'Dosya Çözüldü'), ('SECURITY_ALERT', 'Güvenlik Uyarısı'), ('CONFIG_CHANGE', 'Ayar Değişikliği'), ('API_KEY_CREATE', 'API Key Üretildi'), ('API_KEY_REVOKE', 'API Key İptal Edildi'), ('API_KEY_ROTATE', 'API Key Döndürüldü'), ('API_AUTH_SUCCESS', 'API Doğrulama Başarılı'), ('API_AUTH_FAIL', 'API Doğrulama Başarısız'), ('RATE_LIMIT_HIT', 'Rate Limit Aşıldı'), ('WEBHOOK_VERIFIED', 'Webhook Doğrulandı'), ('WEBHOOK_REJECTED', 'Webhook Reddedildi'), ('SUSPICIOUS_IP', 'Şüpheli IP Erişimi'), ('CORS_VIOLATION', 'CORS İhlali')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('resource', models.CharField(max_length=255)),
                ('project', models.CharField(max_length=50)),
                ('success', models.BooleanField(default=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Güvenlik Denetim Kaydı',
                'verbose_name_plural': 'Güvenlik Denetim Kayıtları',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='erdeniz_sec_event_t_6b0a68_idx'), models.Index(fields=['project', 'timestamp'], name='erdeniz_sec_project_8c1738_idx'), models.Index(fields=['user_id', 'timestamp'], name='erdeniz_sec_user_id_2f0fb0_idx')],
            },
        ),
    ]
